version: '3.5'
services:
  node:
    container_name: ${APP_CONTAINER_NAME}
    build: .
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.nuxt
      - /app/.output
    networks:
      default-network:
        aliases:
          - ${APP_CONTAINER_NAME}.docker

networks:
  default-network:
    external:
      name: digitalbutler-network
